version: '2'
services:
  web:
    image: 'nginx'
    ports:
      - '80:80'
    volumes:
      - c:/docker/html:/usr/share/nginx/html
  mongodb:
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - c:/docker/data/db:/data/db
  nodepop:
    image: 'node'
    ports:
      - '8080:8080'
    volumes:
      - c:/docker/nodepop:/usr/src/app
    depends_on:
      - mongodb
    links:
      - mongodb  
    environment:    
      NODE_ENV: development
